### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lukeyeager** [adjohnson916/magnificent.js#2]
Cool library! What license is this released under? Can you add a LICENSE file?

https://help.github.com/articles/open-source-licensing/

> If you already have a project on GitHub, and it doesn't have a license file or other text indicating what rights you are granting to others, you retain all rights to the software, except those outlined in the GitHub Terms of Service.

I'm pretty sure that means nobody else can use your code at all :disappointed:

http://choosealicense.com/

**Comment by adjohnson916** [comment]
@lukeyeager Thanks! Added MIT license.
