### ISSUE TITLE
Is it possible to destroy your mag instance?

### ISSUE THREAD

**Issue by daviddelusenet** [adjohnson916/magnificent.js#28]
Hi all,

I'm using this code:

    var productdetail = $('[mag-thumb="inner-inline"]');
    productdetail.mag();

Is there anyway to 'unmag' my selector? Thanks!

**Comment by adjohnson916** [comment]
@daviddelusenet Thanks for getting involved.

Currently there's no built-in support for destroying an instance. But it would be a good feature. It would help with memory management in single page applications. Many other jQuery and other DOM-enhancing widgets have this functionality.

Besides unbinding events, do you think it should restore the original HTML (deleting any elements created, undoing any operations on content and attributes of pre-existing elements)?

**Comment by adjohnson916** [comment]
@daviddelusenet Implemented and merged in #30. The new `$host.mag('destroy')` method unbinds events from the two original elements, then replaces them with clones of their original states.

Please review, test, and provide feedback if you can. I won't immediately release it to npm & Bower.
