### ISSUE TITLE
Zoom doesn't work very well on mobile

### ISSUE THREAD

**Issue by daviddelusenet** [adjohnson916/magnificent.js#29]
Hi all,

Even the demo-site: https://andrz.me/magnificent.js/examples/demo/ doesn't work very well on mobile. Any idea on how to improve this? Thanks!

**Comment by adjohnson916** [comment]
@daviddelusenet It is currently relying on Hammer.js `pinch` events. I agree that the behavior is not as smooth as it could be, on certain devices more so than others. To improve, we might have to explore relying on other Hammer.js capabilities or other touch libraries or even raw DOM touch events.

I'm very open to suggestions and pull requests!

For now, I'll also point out that you can try the `mag-control` component to provide alternate means of controlling the zoom and pan on mobile.

**Comment by adjohnson916** [comment]
I should look at how Leaflet.js and/or other map libraries are doing pan & zoom for touch.

E.g.
* https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.TouchZoom.js

**Comment by adjohnson916** [comment]
@daviddelusenet With latest version `2.1.4`, I've released some enhancements to touch zoom behavior based on #34. It should work better now. Please let me know if you notice any results.
