### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by topasi** [adjohnson916/magnificent.js#3]
This plug in not working

**Comment by adjohnson916** [comment]
@topasi Details on particular issue(s) you're having will be necessary for us to help you. Did you look at the source code for the demo to see how it works there?

**Comment by topasi** [comment]
@adjohnson916 Thank for the great plugin. I already solve the problem. I downloaded the package and view the demo folder but it seems not working because the resources files cant locate the bower_component not found.

**Comment by adjohnson916** [comment]
@topasi, that makes sense. You'll need the Bower dependencies installed. Let me know if there's a different issue. Thanks!

**Comment by adjohnson916** [comment]
@topasi, that makes sense. You'll need the Bower dependencies installed. Let me know if there's a different issue. Thanks!
