### ISSUE TITLE
Image spans more than  div in which it is contained 

### ISSUE THREAD

**Issue by mandar-k** [adjohnson916/magnificent.js#35]
<div id="demo-outside" class="demo-class">
		<div data-magnificent="SOME_KEY">
			<div class="inner">
				<img src="img/11.jpg" />
			</div>
		</div>

		
		<div data-magnificent-viewport="SOME_KEY">
			<div class="inner">
				<img src="img/11.jpg" />
			</div>
		</div>
	</div>

markup used 

.demo-class {
	height: 100px;
	width: 100px;
}

css used

**Comment by adjohnson916** [comment]
@mandar-k I believe this is intentional, but you'll have to provide a better example.

**Comment by adjohnson916** [comment]
Closing due to not enough info and lack of response.
