### ISSUE TITLE
Fix the requirements

### ISSUE THREAD

**Issue by Soraph** [adjohnson916/magnificent.js#4]
The plugin need jquery.bridget in order to work correctly, please fix the documentation

**Comment by adjohnson916** [comment]
@Soraph Do you use Bower? All the dependencies are specified in the bower.json file.

With would be good to add a note about this to the documentation.

**Comment by Soraph** [comment]
Didn't use bower, not all the projects can use bower, by just following the instruction you gave on the documentation you can't have a working result

**Comment by adjohnson916** [comment]
Relates to #1.

**Comment by adjohnson916** [comment]
Relates to #1.

**Comment by adjohnson916** [comment]
@Soraph, I've added information to `README.md` under "Usage" indicating the need to include dependencies listed in `bower.json` file. Do you think it should be even more explicitly listed there? I'm trying to reduce dual maintenance of dependency list.

**Comment by Soraph** [comment]
Sorry for the delay, if is ok for you, this evening (after 18 PM GMT) I'll modify your readme in a fork to implement what I think is missing from the docs :-)

**Comment by adjohnson916** [comment]
@Soraph, go for it, thanks!
