### ISSUE TITLE
not working with multiple images!

### ISSUE THREAD

**Issue by amaurya37** [adjohnson916/magnificent.js#45]
How to use with image slider, i have tried to use but zoom if having conflict on it.

**Comment by adjohnson916** [comment]
@amaurya37 Can you provide example code? I can't tell what you're trying to do.

**Comment by macclinson** [comment]
Doesn't work properly when you try to add multiple instances of it in a page, for example, inside a slider like below. How do you initialize it in this case?
                <ul class="carousel">
                  <li>
                    <div class="outer-wrap">
                      <div mag-thumb="outer" class="img-area">
                        <img src="../images/zoom-img-1-thumb.jpg" alt="" />
                      </div>
                      <div class="zoom-area">
                        <div mag-zoom="outer">
                          <img src="../images/zoom-img-1-thumb.jpg" alt="" />
                        </div>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="outer-wrap">
                      <div mag-thumb="outer" class="img-area">
                        <img src="../images/zoom-img-2-thumb.jpg" alt="" />
                      </div>
                      <div class="zoom-area">
                        <div mag-zoom="outer">
                          <img src="../images/zoom-img-2-thumb.jpg" alt="" />
                        </div>
                      </div>
                    </div>
                  </li>
               </ul>

**Comment by adjohnson916** [comment]
@macclinson @amaurya37 You need to you a unique identifier for each instance/pair in the `mag-thumb`/`mag-zoom` attributes. The `mag-thumb="outer"` was just an example.
