### ISSUE TITLE
Fix the CSS

### ISSUE THREAD

**Issue by Soraph** [adjohnson916/magnificent.js#5]
mag-thumb does not need to be positioned with position absolute, it just force you to define heights for the parent element

**Comment by adjohnson916** [comment]
@Soraph, are you able to remove this while still having outer mode examples work? Perhaps I could set absolute position only for outer modes.

**Comment by adjohnson916** [comment]
@Soraph I've added an optional attribute `mag-flow="inline"` on `mag-thumb` element which supports this use case. Added an example to the demo page called "Inner Inline". Please let me know if it doesn't work for you. Thanks.
